---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: williamyeh/ansible
    tag: 'ubuntu16.04'

params:
  SKYWAY_INSTALLER:
  VCENTER_HOST:
  VCENTER_USR:
  VCENTER_PWD:
  VCENTER_DATACENTER:
  VCENTER_DATASTORE:
  VCENTER_CLUSTER:
  VCENTER_RP:
  VCENTER_MANAGER:
  NTPSERVERS:
  MGMT_PORTGROUP:
  DNSSERVER:
  DNSDOMAIN:
  DEFAULTGATEWAY:
  NETMASK:
  COMPUTE_VCENTER_HOST:
  COMPUTE_VCENTER_USR:
  COMPUTE_VCENTER_PWD:
  COMPUTE_VCENTER_CLUSTER:
  COMPUTE_VCENTER_MANAGER:
  EDGE_VCENTER_HOST:
  EDGE_VCENTER_USR:
  EDGE_VCENTER_PWD:
  EDGE_VCENTER_DATACENTER:
  EDGE_VCENTER_DATASTORE:
  EDGE_VCENTER_CLUSTER:
  SKYWAY_MANAGER_VM_NAME:
  SKYWAY_MANAGER_HOST_NAME:
  SKYWAY_MANAGER_IP:
  SKYWAY_MANAGER_ADMIN_PWD:
  SKYWAY_MANAGER_ROOT_PWD:
  SKYWAY_EDGE_HOST_PREFIX:
  SKYWAY_EDGE_VM_NAME_PREFIX:
  SKYWAY_EDGE_IPS:
  SKYWAY_EDGE_ROOT_PWD:
  SKYWAY_MGR_DEPLOY_SIZE:
  SKYWAY_EDGE_DEPLOY_SIZE:
  SKYWAY_EDGE_CLUSTER:
  ENABLE_ANSIBLE_DEBUG:
  GIT_KEY:
  azure_cli_application_id:
  azure_cli_application_key:
  azure_cli_tenant_id:
  azure_iot_hub_name:
  azure_iot_group:
  aws_access_key_id:
  aws_secret_access_key:
  greengrass_s3_bucket:
  greengrass_group_names:
  greengrass_device_stub:
  greengrass_device_count:
  greengrass_deploy:

inputs:
  - name: skyway-pipeline
  - name: skyway-automation
  - name: ansible-role-azure-iot
  - name: ansible-role-azure-edge
  - name: ansible-aws-greengrass
run:
  path: skyway-pipeline/tasks/install-skyway/task.sh
