---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: huxoll/cloud-metaclient
    tag: 'latest'

params:
  SKYWAY_INSTALLER:
  VCENTER_HOST:
  VCENTER_USR:
  VCENTER_PWD:
  VCENTER_DATACENTER:
  VCENTER_DATASTORE:
  VCENTER_CLUSTER:
  VCENTER_RP:
  VCENTER_MANAGER:
  NTPSERVERS:
  MGMT_PORTGROUP:
  DNSSERVER:
  DNSDOMAIN:
  DEFAULTGATEWAY:
  NETMASK:
  SKYWAY_MANAGER_VM_NAME:
  SKYWAY_MANAGER_HOST_NAME:
  SKYWAY_MANAGER_IP:
  SKYWAY_MANAGER_ADMIN_PWD:
  SKYWAY_MANAGER_ROOT_PWD:
  SKYWAY_EDGE_HOST_PREFIX:
  SKYWAY_EDGE_VM_NAME_PREFIX:
  SKYWAY_EDGE_IPS:
  SKYWAY_EDGE_ROOT_PWD:
  SKYWAY_MGR_DEPLOY_SIZE:
  SKYWAY_EDGE_DEPLOY_SIZE:
  SKYWAY_EDGE_CLUSTER:
  ENABLE_ANSIBLE_DEBUG:
  GIT_KEY:
  azure_cli_application_id:
  azure_cli_application_key:
  azure_cli_tenant_id:
  azure_iot_hub_name:
  azure_iot_group:
  aws_access_key:
  aws_secret_key:
  greengrass_s3_bucket:
  greengrass_group_names:
  greengrass_device_stub:
  greengrass_device_count:
  greengrass_deploy:
  skyway_edges:
  skyway_edge_start:
  skyway_edge_end:

inputs:
  - name: skyway-pipeline
  - name: skyway-automation
  - name: ansible-role-azure-iot
  - name: ansible-role-azure-edge
  - name: ansible-aws-greengrass

run:
  path: skyway-pipeline/tasks/generic-ansible/task.sh
  args:
    - --host-role
    - azure-driver=huxoll.azure-cli
    - --host-role
    - greengrass-driver=vmware.awscli
