---

platform: linux

image_resource:
  type: docker-image
  source: {repository: williamyeh/ansible:ubuntu16.04}
  
params:
  SKYWAY_INSTALLER:
  VCENTER_HOST:
  VCENTER_USR:
  VCENTER_PWD:
  VCENTER_DATACENTER:
  VCENTER_DATASTORE:
  VCENTER_CLUSTER:
  VCENTER_RP:
  VCENTER_MANAGER:
  NTPSERVERS:
  MGMT_PORTGROUP:
  DNSSERVER:
  DNSDOMAIN:
  DEFAULTGATEWAY:
  NETMASK:
  COMPUTE_VCENTER_HOST:
  COMPUTE_VCENTER_USR:
  COMPUTE_VCENTER_PWD:
  COMPUTE_VCENTER_CLUSTER:
  COMPUTE_VCENTER_MANAGER:
  EDGE_VCENTER_HOST:
  EDGE_VCENTER_USR:
  EDGE_VCENTER_PWD:
  EDGE_VCENTER_DATACENTER:
  EDGE_VCENTER_DATASTORE:
  EDGE_VCENTER_CLUSTER:
  SKYWAY_MANAGER_VM_NAME:
  SKYWAY_MANAGER_HOST_NAME:
  SKYWAY_MANAGER_IP:
  SKYWAY_MANAGER_ADMIN_PWD:
  SKYWAY_MANAGER_ROOT_PWD:
  SKYWAY_EDGE_HOST_PREFIX:
  SKYWAY_EDGE_VM_NAME_PREFIX:
  SKYWAY_EDGE_IPS:
  SKYWAY_EDGE_ROOT_PWD:
  SKYWAY_MGR_DEPLOY_SIZE:
  SKYWAY_EDGE_DEPLOY_SIZE:
  SKYWAY_EDGE_CLUSTER:
  ENABLE_ANSIBLE_DEBUG:
  GIT_KEY:


inputs:
  - name: skyway-pipeline
  - name: skyway-automation

run:
  path: skyway-pipeline/tasks/initialize-cloud-iot/task.sh
