---
# Use reference instead of repeating the skyway params
skyway_params: &skyway-params
  SKYWAY_INSTALLER: ((skyway_installer))
  VCENTER_HOST: ((vcenter_host))
  VCENTER_USR: ((vcenter_usr))
  VCENTER_PWD: ((vcenter_pwd))
  VCENTER_DATACENTER: ((vcenter_datacenter))
  VCENTER_DATASTORE: ((vcenter_datastore))
  VCENTER_CLUSTER: ((vcenter_cluster))
  VCENTER_MANAGER: ((vcenter_manager))
  VCENTER_RP: ((vcenter_rp))
  NTPSERVERS: ((ntpservers))
  MGMT_PORTGROUP: ((mgmt_portgroup))
  DNSSERVER: ((dnsserver))
  DNSDOMAIN: ((dnsdomain))
  DEFAULTGATEWAY: ((defaultgateway))
  NETMASK: ((netmask))
  COMPUTE_VCENTER_HOST: ((compute_vcenter_host))
  COMPUTE_VCENTER_USR: ((compute_vcenter_usr))
  COMPUTE_VCENTER_PWD: ((compute_vcenter_pwd))
  COMPUTE_VCENTER_CLUSTER: ((compute_vcenter_cluster))
  COMPUTE_VCENTER_MANAGER: ((compute_vcenter_manager))
  EDGE_VCENTER_HOST: ((edge_vcenter_host))
  EDGE_VCENTER_USR: ((edge_vcenter_usr))
  EDGE_VCENTER_PWD: ((edge_vcenter_pwd))
  EDGE_VCENTER_DATACENTER: ((edge_vcenter_datacenter))
  EDGE_VCENTER_DATASTORE: ((edge_vcenter_datastore))
  EDGE_VCENTER_CLUSTER: ((edge_vcenter_cluster))
  SKYWAY_MANAGER_VM_NAME: ((skyway_manager_vm_name))
  SKYWAY_MANAGER_HOST_NAME: ((skyway_manager_host_name))
  SKYWAY_MANAGER_IP: ((skyway_manager_ip))
  SKYWAY_MANAGER_ADMIN_USER: ((skyway_manager_admin_user))
  SKYWAY_MANAGER_ADMIN_PWD: ((skyway_manager_admin_pwd))
  SKYWAY_MANAGER_ROOT_PWD: ((skyway_manager_root_pwd))
  SKYWAY_EDGE_HOST_PREFIX: ((skyway_edge_host_prefix))
  SKYWAY_EDGE_VM_NAME_PREFIX: ((skyway_edge_vm_name_prefix))
  SKYWAY_EDGE_IPS: ((skyway_edge_ips))
  SKYWAY_EDGE_ROOT_PWD: ((skyway_edge_root_pwd))
  SKYWAY_MGR_DEPLOY_SIZE: ((skyway_mgr_deploy_size))
  SKYWAY_EDGE_DEPLOY_SIZE: ((skyway_edge_deploy_size))
  SKYWAY_EDGE_CLUSTER: ((skyway_edge_cluster))
  ENABLE_ANSIBLE_DEBUG: ((enable_ansible_debug))
  GIT_KEY: ((git_key))

groups:

- name: full-install
  jobs:
  - install-skyway
  - add-skyway-edge-gateway
  - config-skyway-extras

- name: base-install
  jobs:
  - standalone-install-skyway

- name: add-edge-gateway
  jobs:
  - standalone-add-skyway-edge-gateway

- name: config-skyway-extras
  jobs:
  - standalone-config-skyway-extras

# - name: cleanup
#   jobs:
#   - uninstall-skyway

resource_types:
- name: file-url
  type: docker-image
  source:
    repository: pivotalservices/concourse-curl-resource

resources:
- name: skyway-pipeline
  type: git
  source:
    uri: git@gitlab.eng.vmware.com:vmworld2018/skyway-concourse-deploy.git
    branch: master
    private_key: ((git_key))

- name: skyway-automation
  type: git
  source:
    uri: git@gitlab.eng.vmware.com:vmworld2018/skyway-automation
    branch: master
    private_key: ((git_key))

- name: base-ova
  type: file-url
  source:
    #username: username
    #password: password
    url: ((binary_webserver))/((base_ova))
    filename: ((base_ova))
    skip_ssl_verification: true

# Download from https://my.vmware.com/group/vmware/details?productId=614&downloadGroup=OVFTOOL420#
- name: ovftool
  type: file-url
  source:
    #username: username
    #password: password
    url: ((binary_webserver))/((ovftool_image))
    filename: ((ovftool_image))
    skip_ssl_verification: true

jobs:

- name: skyway-deploy
  plan:
  - aggregate:
    - get: skyway-pipeline
    - get: skyway-automation
    - get: base-ova
    - get: ovftool

  - task: install-skyway
    file: skyway-pipeline/tasks/install-skyway/task.yml
    params: *skyway-params

- name: add-skyway-edge-gateway
  plan:
  - aggregate:
    - get: skyway-pipeline
    - get: skyway-automation
      params: {globs: []}
      passed: [skyway-deploy]
      trigger: true

  - task: add-skyway-edge-gateway
    file: skyway-pipeline/tasks/add-skyway-edge-gateway/task.yml
    params: *skyway-params

- name: config-skyway-extras
  plan:
  - aggregate:
    - get: skyway-pipeline
    - get: skyway-automation
      params: {globs: []}
      passed: [add-skyway-edge-gateway]
      trigger: true

  - task: config-skyway-extras
    file: skyway-pipeline/tasks/config-skyway-extras/task.yml
    params: *skyway-params

- name: standalone-install-skyway
  plan:
  - aggregate:
    - get: skyway-pipeline
    - get: skyway-automation
    - get: base-ova
    - get: ovftool

  - task: install-skyway
    file: skyway-pipeline/tasks/install-skyway/task.yml
    params: *skyway-params

- name: standalone-add-skyway-edge-gateway
  plan:
  - aggregate:
    - get: skyway-pipeline
    - get: skyway-automation
      params: {globs: []}

  - task: add-skyway-edge-gateway
    file: skyway-pipeline/tasks/add-skyway-edge-gateway/task.yml
    params: *skyway-params

- name: standalone-config-skyway-extras
  plan:
  - aggregate:
    - get: skyway-pipeline
    - get: skyway-automation
      params: {globs: []}

  - task: config-skyway-extras
    file: skyway-pipeline/tasks/config-skyway-extras/task.yml
    params: *skyway-params
